/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetoresVarejoRouteImport } from './routes/setores/varejo'
import { Route as SetoresSaudeRouteImport } from './routes/setores/saude'
import { Route as SetoresSaasB2bRouteImport } from './routes/setores/saas-b2b'
import { Route as SetoresLogisticaRouteImport } from './routes/setores/logistica'
import { Route as SetoresIndustriaRouteImport } from './routes/setores/industria'
import { Route as SetoresFintechRouteImport } from './routes/setores/fintech'
import { Route as SetoresEducacaoRouteImport } from './routes/setores/educacao'
import { Route as ServicosMobileRouteImport } from './routes/servicos/mobile'
import { Route as ServicosInteligenciaArtificialRouteImport } from './routes/servicos/inteligencia-artificial'
import { Route as ServicosIntegracaoDeSistemasRouteImport } from './routes/servicos/integracao-de-sistemas'
import { Route as ServicosErpCrmRouteImport } from './routes/servicos/erp-crm'
import { Route as ServicosDesenvolvimentoWebRouteImport } from './routes/servicos/desenvolvimento-web'
import { Route as ServicosConsultoriaRouteImport } from './routes/servicos/consultoria'
import { Route as ServicosAutomacaoRouteImport } from './routes/servicos/automacao'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetoresVarejoRoute = SetoresVarejoRouteImport.update({
  id: '/setores/varejo',
  path: '/setores/varejo',
  getParentRoute: () => rootRouteImport,
} as any)
const SetoresSaudeRoute = SetoresSaudeRouteImport.update({
  id: '/setores/saude',
  path: '/setores/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const SetoresSaasB2bRoute = SetoresSaasB2bRouteImport.update({
  id: '/setores/saas-b2b',
  path: '/setores/saas-b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const SetoresLogisticaRoute = SetoresLogisticaRouteImport.update({
  id: '/setores/logistica',
  path: '/setores/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const SetoresIndustriaRoute = SetoresIndustriaRouteImport.update({
  id: '/setores/industria',
  path: '/setores/industria',
  getParentRoute: () => rootRouteImport,
} as any)
const SetoresFintechRoute = SetoresFintechRouteImport.update({
  id: '/setores/fintech',
  path: '/setores/fintech',
  getParentRoute: () => rootRouteImport,
} as any)
const SetoresEducacaoRoute = SetoresEducacaoRouteImport.update({
  id: '/setores/educacao',
  path: '/setores/educacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosMobileRoute = ServicosMobileRouteImport.update({
  id: '/servicos/mobile',
  path: '/servicos/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosInteligenciaArtificialRoute =
  ServicosInteligenciaArtificialRouteImport.update({
    id: '/servicos/inteligencia-artificial',
    path: '/servicos/inteligencia-artificial',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosIntegracaoDeSistemasRoute =
  ServicosIntegracaoDeSistemasRouteImport.update({
    id: '/servicos/integracao-de-sistemas',
    path: '/servicos/integracao-de-sistemas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosErpCrmRoute = ServicosErpCrmRouteImport.update({
  id: '/servicos/erp-crm',
  path: '/servicos/erp-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosDesenvolvimentoWebRoute =
  ServicosDesenvolvimentoWebRouteImport.update({
    id: '/servicos/desenvolvimento-web',
    path: '/servicos/desenvolvimento-web',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosConsultoriaRoute = ServicosConsultoriaRouteImport.update({
  id: '/servicos/consultoria',
  path: '/servicos/consultoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosAutomacaoRoute = ServicosAutomacaoRouteImport.update({
  id: '/servicos/automacao',
  path: '/servicos/automacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/servicos/automacao': typeof ServicosAutomacaoRoute
  '/servicos/consultoria': typeof ServicosConsultoriaRoute
  '/servicos/desenvolvimento-web': typeof ServicosDesenvolvimentoWebRoute
  '/servicos/erp-crm': typeof ServicosErpCrmRoute
  '/servicos/integracao-de-sistemas': typeof ServicosIntegracaoDeSistemasRoute
  '/servicos/inteligencia-artificial': typeof ServicosInteligenciaArtificialRoute
  '/servicos/mobile': typeof ServicosMobileRoute
  '/setores/educacao': typeof SetoresEducacaoRoute
  '/setores/fintech': typeof SetoresFintechRoute
  '/setores/industria': typeof SetoresIndustriaRoute
  '/setores/logistica': typeof SetoresLogisticaRoute
  '/setores/saas-b2b': typeof SetoresSaasB2bRoute
  '/setores/saude': typeof SetoresSaudeRoute
  '/setores/varejo': typeof SetoresVarejoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/servicos/automacao': typeof ServicosAutomacaoRoute
  '/servicos/consultoria': typeof ServicosConsultoriaRoute
  '/servicos/desenvolvimento-web': typeof ServicosDesenvolvimentoWebRoute
  '/servicos/erp-crm': typeof ServicosErpCrmRoute
  '/servicos/integracao-de-sistemas': typeof ServicosIntegracaoDeSistemasRoute
  '/servicos/inteligencia-artificial': typeof ServicosInteligenciaArtificialRoute
  '/servicos/mobile': typeof ServicosMobileRoute
  '/setores/educacao': typeof SetoresEducacaoRoute
  '/setores/fintech': typeof SetoresFintechRoute
  '/setores/industria': typeof SetoresIndustriaRoute
  '/setores/logistica': typeof SetoresLogisticaRoute
  '/setores/saas-b2b': typeof SetoresSaasB2bRoute
  '/setores/saude': typeof SetoresSaudeRoute
  '/setores/varejo': typeof SetoresVarejoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/servicos/automacao': typeof ServicosAutomacaoRoute
  '/servicos/consultoria': typeof ServicosConsultoriaRoute
  '/servicos/desenvolvimento-web': typeof ServicosDesenvolvimentoWebRoute
  '/servicos/erp-crm': typeof ServicosErpCrmRoute
  '/servicos/integracao-de-sistemas': typeof ServicosIntegracaoDeSistemasRoute
  '/servicos/inteligencia-artificial': typeof ServicosInteligenciaArtificialRoute
  '/servicos/mobile': typeof ServicosMobileRoute
  '/setores/educacao': typeof SetoresEducacaoRoute
  '/setores/fintech': typeof SetoresFintechRoute
  '/setores/industria': typeof SetoresIndustriaRoute
  '/setores/logistica': typeof SetoresLogisticaRoute
  '/setores/saas-b2b': typeof SetoresSaasB2bRoute
  '/setores/saude': typeof SetoresSaudeRoute
  '/setores/varejo': typeof SetoresVarejoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/contato'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/servicos/automacao'
    | '/servicos/consultoria'
    | '/servicos/desenvolvimento-web'
    | '/servicos/erp-crm'
    | '/servicos/integracao-de-sistemas'
    | '/servicos/inteligencia-artificial'
    | '/servicos/mobile'
    | '/setores/educacao'
    | '/setores/fintech'
    | '/setores/industria'
    | '/setores/logistica'
    | '/setores/saas-b2b'
    | '/setores/saude'
    | '/setores/varejo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/contato'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/servicos/automacao'
    | '/servicos/consultoria'
    | '/servicos/desenvolvimento-web'
    | '/servicos/erp-crm'
    | '/servicos/integracao-de-sistemas'
    | '/servicos/inteligencia-artificial'
    | '/servicos/mobile'
    | '/setores/educacao'
    | '/setores/fintech'
    | '/setores/industria'
    | '/setores/logistica'
    | '/setores/saas-b2b'
    | '/setores/saude'
    | '/setores/varejo'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/contato'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/servicos/automacao'
    | '/servicos/consultoria'
    | '/servicos/desenvolvimento-web'
    | '/servicos/erp-crm'
    | '/servicos/integracao-de-sistemas'
    | '/servicos/inteligencia-artificial'
    | '/servicos/mobile'
    | '/setores/educacao'
    | '/setores/fintech'
    | '/setores/industria'
    | '/setores/logistica'
    | '/setores/saas-b2b'
    | '/setores/saude'
    | '/setores/varejo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  ContatoRoute: typeof ContatoRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ServicosAutomacaoRoute: typeof ServicosAutomacaoRoute
  ServicosConsultoriaRoute: typeof ServicosConsultoriaRoute
  ServicosDesenvolvimentoWebRoute: typeof ServicosDesenvolvimentoWebRoute
  ServicosErpCrmRoute: typeof ServicosErpCrmRoute
  ServicosIntegracaoDeSistemasRoute: typeof ServicosIntegracaoDeSistemasRoute
  ServicosInteligenciaArtificialRoute: typeof ServicosInteligenciaArtificialRoute
  ServicosMobileRoute: typeof ServicosMobileRoute
  SetoresEducacaoRoute: typeof SetoresEducacaoRoute
  SetoresFintechRoute: typeof SetoresFintechRoute
  SetoresIndustriaRoute: typeof SetoresIndustriaRoute
  SetoresLogisticaRoute: typeof SetoresLogisticaRoute
  SetoresSaasB2bRoute: typeof SetoresSaasB2bRoute
  SetoresSaudeRoute: typeof SetoresSaudeRoute
  SetoresVarejoRoute: typeof SetoresVarejoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setores/varejo': {
      id: '/setores/varejo'
      path: '/setores/varejo'
      fullPath: '/setores/varejo'
      preLoaderRoute: typeof SetoresVarejoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setores/saude': {
      id: '/setores/saude'
      path: '/setores/saude'
      fullPath: '/setores/saude'
      preLoaderRoute: typeof SetoresSaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setores/saas-b2b': {
      id: '/setores/saas-b2b'
      path: '/setores/saas-b2b'
      fullPath: '/setores/saas-b2b'
      preLoaderRoute: typeof SetoresSaasB2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setores/logistica': {
      id: '/setores/logistica'
      path: '/setores/logistica'
      fullPath: '/setores/logistica'
      preLoaderRoute: typeof SetoresLogisticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setores/industria': {
      id: '/setores/industria'
      path: '/setores/industria'
      fullPath: '/setores/industria'
      preLoaderRoute: typeof SetoresIndustriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setores/fintech': {
      id: '/setores/fintech'
      path: '/setores/fintech'
      fullPath: '/setores/fintech'
      preLoaderRoute: typeof SetoresFintechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setores/educacao': {
      id: '/setores/educacao'
      path: '/setores/educacao'
      fullPath: '/setores/educacao'
      preLoaderRoute: typeof SetoresEducacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/mobile': {
      id: '/servicos/mobile'
      path: '/servicos/mobile'
      fullPath: '/servicos/mobile'
      preLoaderRoute: typeof ServicosMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/inteligencia-artificial': {
      id: '/servicos/inteligencia-artificial'
      path: '/servicos/inteligencia-artificial'
      fullPath: '/servicos/inteligencia-artificial'
      preLoaderRoute: typeof ServicosInteligenciaArtificialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/integracao-de-sistemas': {
      id: '/servicos/integracao-de-sistemas'
      path: '/servicos/integracao-de-sistemas'
      fullPath: '/servicos/integracao-de-sistemas'
      preLoaderRoute: typeof ServicosIntegracaoDeSistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/erp-crm': {
      id: '/servicos/erp-crm'
      path: '/servicos/erp-crm'
      fullPath: '/servicos/erp-crm'
      preLoaderRoute: typeof ServicosErpCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/desenvolvimento-web': {
      id: '/servicos/desenvolvimento-web'
      path: '/servicos/desenvolvimento-web'
      fullPath: '/servicos/desenvolvimento-web'
      preLoaderRoute: typeof ServicosDesenvolvimentoWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/consultoria': {
      id: '/servicos/consultoria'
      path: '/servicos/consultoria'
      fullPath: '/servicos/consultoria'
      preLoaderRoute: typeof ServicosConsultoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/automacao': {
      id: '/servicos/automacao'
      path: '/servicos/automacao'
      fullPath: '/servicos/automacao'
      preLoaderRoute: typeof ServicosAutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  ContatoRoute: ContatoRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ServicosAutomacaoRoute: ServicosAutomacaoRoute,
  ServicosConsultoriaRoute: ServicosConsultoriaRoute,
  ServicosDesenvolvimentoWebRoute: ServicosDesenvolvimentoWebRoute,
  ServicosErpCrmRoute: ServicosErpCrmRoute,
  ServicosIntegracaoDeSistemasRoute: ServicosIntegracaoDeSistemasRoute,
  ServicosInteligenciaArtificialRoute: ServicosInteligenciaArtificialRoute,
  ServicosMobileRoute: ServicosMobileRoute,
  SetoresEducacaoRoute: SetoresEducacaoRoute,
  SetoresFintechRoute: SetoresFintechRoute,
  SetoresIndustriaRoute: SetoresIndustriaRoute,
  SetoresLogisticaRoute: SetoresLogisticaRoute,
  SetoresSaasB2bRoute: SetoresSaasB2bRoute,
  SetoresSaudeRoute: SetoresSaudeRoute,
  SetoresVarejoRoute: SetoresVarejoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
